version: "3.8"
services:
  database:
    image: mongo
    container_name: mern-stack-authentication-component-database
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - mern-stack-authentication-component-network

  backend:
    depends_on:
      - database
    container_name: mern-stack-authentication-component-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    env_file: ./server/.env
    ports:
      - "8000:8000"
    networks:
      - mern-stack-authentication-component-network

  frontend:
    depends_on:
      - backend
    container_name: mern-stack-authentication-component-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./client/.env
    ports:
      - "3000:3000"
    networks:
      - mern-stack-authentication-component-network  

volumes:
  mongo:

networks:
  mern-stack-authentication-component-network:
    driver: bridge