version: "3.8"
services:
  database:
    image: mongo
    container_name: msac-database
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - msac-network

  backend:
    depends_on:
      - database
    container_name: msac-backend
    environment:
      PORT: ${PORT}
      DOCKER_DB_URL: ${DOCKER_DB_URL}
      REMOTE_DB_URL: ${REMOTE_DB_URL}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      TOKEN_SECRET_KEY_EXPIRY: ${TOKEN_SECRET_KEY_EXPIRY}
      GMAIL_EMAIL: ${GMAIL_EMAIL}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    networks:
      - msac-network

  frontend:
    depends_on:
      - backend
    container_name: msac-frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - msac-network  

volumes:
  mongo:
    driver: local

networks:
  msac-network:
    driver: bridge