version: "3.8"
services:
  database:
    image: mongo
    container_name: msac-database
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - msac-network

  backend:
    depends_on:
      - database
    container_name: msac-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
    env_file: ./server/.env
    ports:
      - "8000:8000"
    networks:
      - msac-network

  frontend:
    depends_on:
      - backend
    container_name: msac-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file: ./client/.env
    ports:
      - "3000:3000"
    networks:
      - msac-network  

volumes:
  mongo:
    driver: local

networks:
  msac-network:
    driver: bridge